name = "merch-worker"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
FRONTEND_URL = "https://shop.ritvikmalhotra.tech"

[[d1_databases]]
binding = "DB"
database_name = "merch-db"
database_id = "c12370a9-b295-42f5-9577-3c7f109741f3"
